name: Use Supabase Key

on: [push]

jobs:
  test-key:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

    steps:
      - name: Print first 10 characters of the key (safe!)
        run: echo "${SUPABASE_ANON_KEY:0:10}..."
